// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrgEstudiantes.Comunes.Datos;

namespace OrgEstudiantes.Comunes.Migrations
{
    [DbContext(typeof(dbContex))]
    [Migration("20220309153004_Completatablaestudiante")]
    partial class Completatablaestudiante
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("OrgEstudiantes.Comunes.Datos.database.Estudiantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CodEstudiante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodMateria")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NombreEstudiante")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NombreMateria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodMateria" }, "Uq_Estudiantes_CodEstudiantes")
                        .IsUnique();

                    b.HasIndex(new[] { "CodMateria" }, "Uq_Estudiantes_CodMareria")
                        .IsUnique();

                    b.ToTable("Alumno");
                });
#pragma warning restore 612, 618
        }
    }
}
